name: ALFA policy project
on:
  push:

jobs:
  build-and-test-alfa:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout project sources
      uses: actions/checkout@v4
         
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3        
    
    - name: Build and test
      env:
        AXIOMATICS_ACCESS_KEY_ID: ${{ secrets.AXIOMATICS_ACCESS_KEY_ID}}
        AXIOMATICS_SECRET_ACCESS_KEY: ${{ secrets.AXIOMATICS_SECRET_ACCESS_KEY }}
      run: ./gradlew test buildAuthzDomain
